"""Generate a real PhysX occupancy preview from the extracted static scene.
No pixel painting; gray cells are generated by Isaac Sim's native mapper.
"""
from pathlib import Path
import json
HERE=Path(__file__).resolve().parent
from isaacsim import SimulationApp
app=SimulationApp({'headless':True,'width':64,'height':64,'disable_viewport_updates':True})
import omni.usd, omni.timeline, omni.physx
from isaacsim.core.utils.extensions import enable_extension
enable_extension('isaacsim.asset.gen.omap')
from isaacsim.asset.gen.omap.bindings import _omap
from pxr import UsdGeom, UsdPhysics, PhysxSchema
import numpy as np
from PIL import Image
ctx=omni.usd.get_context()
s=ctx.get_stage()
s.GetRootLayer().subLayerPaths.append(str(HERE/'static_collision_validation.usdc'))
UsdGeom.SetStageMetersPerUnit(s,1)
UsdGeom.SetStageUpAxis(s,UsdGeom.Tokens.z)
for _ in range(15):app.update()
ps=PhysxSchema.PhysxSceneAPI.Apply(s.GetPrimAtPath('/World/PhysicsScene'))
ps.CreateEnableGPUDynamicsAttr(False)
ps.CreateBroadphaseTypeAttr('MBP')
for _ in range(3):app.update()
tl=omni.timeline.get_timeline_interface()
tl.play()
for _ in range(3):app.update()
g=_omap.acquire_omap_interface()
g.set_cell_size(.05)
g.set_transform((0,0,0),(-49.50,-9.10,.05),(24.95,23.15,1.0))
g.update()
print('GENERATING_HOSPITAL_MAP',flush=True)
g.generate()
app.update()
d=g.get_dimensions()
raw=np.array(g.get_buffer(),dtype=np.float32).reshape((d[1],d[0]))
np.save(HERE/'native_occupancy_buffer.npy',raw)
lo=list(g.get_min_bound())
hi=list(g.get_max_bound())
# The native buffer has X decreasing across columns and Y increasing down rows.
# Match the extension's 180-degree ROS export orientation.
image=np.where(raw==1,0,np.where(raw==0,255,127)).astype(np.uint8)
image=np.rot90(image,2)
world_grid=np.fliplr(raw)
maps=HERE.parents[1]/'src/nova_carter/carter_navigation/maps'
base=maps/'hospital_integration_human_map_excluded'
Image.fromarray(image).save(str(base)+'.png')
# Match compute_coordinates() and ROS export in this installed Isaac Sim UI.
yaml_origin=[lo[0]+.025,lo[1]+.025,0.0]
Path(str(base)+'.yaml').write_text(f'image: {base.name}.png\nresolution: 0.05\norigin: {yaml_origin}\nnegate: 0\noccupied_thresh: 0.65\nfree_thresh: 0.196\n')
report=json.loads((HERE/'exclusion_report.json').read_text())
checks={}
for region in report['regions']:
    x0,y0,x1,y1=region['bounds_xy']
    # Ignore the collision boundary and existing furniture/walls.
    c0=int(np.ceil((x0+.20-lo[0])/.05));c1=int(np.floor((x1-.20-lo[0])/.05))
    r0=int(np.ceil((y0+.20-lo[1])/.05));r1=int(np.floor((y1-.20-lo[1])/.05))
    crop=world_grid[r0:r1,c0:c1]
    counts={'unknown':int(((crop!=0)&(crop!=1)).sum()),
            'free':int((crop==0).sum()),'occupied':int((crop==1).sum())}
    checks[region['name']]={'interior_cells':int(crop.size),'counts':counts}
    assert counts['free']==0, f"Free-space leak into {region['name']}"
    assert counts['unknown']>0, f"No unknown interior in {region['name']}"
result={'dimensions':[d[0],d[1]],'min_bound':lo,'max_bound':hi,
        'counts':{'unknown':int(((raw!=0)&(raw!=1)).sum()),
                  'free':int((raw==0).sum()),'occupied':int((raw==1).sum())},
        'region_checks':checks,'source':'Native Isaac Sim PhysX mapper; static collision extract',
        'omitted_dynamic_assets':report['validation_omissions']}
(HERE/'map_validation.json').write_text(json.dumps(result,indent=2)+'\n')
print('MAP_RESULT',json.dumps(result),flush=True)
tl.stop()
del g
for _ in range(3):app.update()
app.close()
